/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DockerComposeBuilderRouteImport } from './routes/docker/compose-builder'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DockerComposeBuilderRoute = DockerComposeBuilderRouteImport.update({
  id: '/docker/compose-builder',
  path: '/docker/compose-builder',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docker/compose-builder': typeof DockerComposeBuilderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docker/compose-builder': typeof DockerComposeBuilderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docker/compose-builder': typeof DockerComposeBuilderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docker/compose-builder'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docker/compose-builder'
  id: '__root__' | '/' | '/docker/compose-builder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DockerComposeBuilderRoute: typeof DockerComposeBuilderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docker/compose-builder': {
      id: '/docker/compose-builder'
      path: '/docker/compose-builder'
      fullPath: '/docker/compose-builder'
      preLoaderRoute: typeof DockerComposeBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DockerComposeBuilderRoute: DockerComposeBuilderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
